# Site settings
title: Omar the Analyst
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Omar Almukhtar
user_description: I'm a Junior Data Analyst from Saudi Arabia, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Enspire group, a Dubai based startup trying to improve the world through collaborative giving. I'm the first Physicist/Data Analyst they hired to work on the platform.
user_title: Physicist & Analyst
email: Omar.Mawlod1@gmail.com
# twitter_username: lorem_ipsum
instagram_username: Omar-the-Analyst
facebook_username: Omar-the-Analyst
linkedin_username: Omars1
github_username:  Omars32
medium_username: Omar-the-Analyst
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
